// Generated by CoffeeScript 1.3.3
var Parse, Profile, Q;

Q = require("q");

Parse = require("parse").Parse;

Profile = (function() {

  function Profile() {}

  Profile.create = function(nameValuePairs){
    
  }

  Profile.findByAttributes = function(nameValuePairs) {
    var Profiles, deferred, error, name, profileQuery, success, value;
    
    deferred = Q.defer();
    
    Profiles = Parse.Object.extend("Profiles");
    profileQuery = new Parse.Query(Profiles);
    for (name in nameValuePairs) {
      value = nameValuePairs[name];
      profileQuery.equalTo(name, value);
    }

    success = function(results) {
      return deferred.resolve(results);
    };
    error = function(err) {
      return deferred.reject(err);
    };
    
    profileQuery.find().then(success, error);
    
    return deferred.promise;
  };

  return Profile;

})();

module.exports = Profile;