// Generated by CoffeeScript 1.7.1
var App, _3Ajax, _3Model,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_3Model = require("3vot-model");

_3Ajax = require("3vot-model/lib/ajax");

App = (function(_super) {
  __extends(App, _super);

  function App() {
    return App.__super__.constructor.apply(this, arguments);
  }

  App.configure("App", "name", "app_name", "billing", "marketing", "version", "user_name", "public_dev_key");

  App.extend(_3Ajax);

  App.extend(_3Ajax.Auto);

  App.querySimpleByNameAndProfileSecurity = "select apps.id,apps.sales,apps.name, apps.version from apps inner join profiles on (apps.profile_id = profiles.id) where profiles.user_name = $1  and apps.name =  $2";

  return App;

})(_3Model.Model);

module.exports = App;