// Generated by CoffeeScript 1.7.1
var Q, Store, _3Ajax, _3Model,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_3Model = require("3vot-model");

_3Ajax = require("3vot-model/lib/ajax");

Q = require("q");

Store = (function(_super) {
  __extends(Store, _super);

  function Store() {
    return Store.__super__.constructor.apply(this, arguments);
  }

  Store.configure("Store", "name", "profile_id", "apps", "public_dev_key", "user_name");

  Store.extend(_3Ajax);

  Store.extend(_3Ajax.Auto);

  return Store;

})(_3Model.Model);

module.exports = Store;